service: toiki
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  profile: personal-toiki
  memorySize: 256
  timeout: 10

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /articles
          method: GET
          cors: true
      - http:
          path: /article/{id}
          method: GET
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8888
